<a href="https://colab.research.google.com/github/HaaidQazi/MLProject/blob/main/CreditCardFraudDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset to a Pandas Dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
71391,54278,1.039072,-0.213656,0.431251,0.918611,-0.621456,-0.667224,0.134553,-0.181427,0.400214,...,-0.167499,-0.510090,-0.079011,0.444677,0.428995,0.256921,-0.039011,0.031128,106.85,0.0
71392,54279,-5.084290,-4.002881,1.329865,-0.573442,-0.690674,0.019033,0.844001,-0.466913,0.381563,...,-0.962575,0.808686,2.249283,0.165161,1.093631,-0.235500,-0.055029,-0.272360,314.31,0.0
71393,54280,1.441869,-0.411978,-0.357381,-0.981390,-0.244335,-0.292055,-0.242842,-0.091250,-1.241760,...,-0.832744,-2.041536,0.134713,-0.883851,0.100577,0.680045,-0.083669,-0.013649,11.97,0.0
71394,54280,-0.441533,0.363429,1.434158,-2.116500,-0.582532,-1.354317,0.886887,-0.335278,0.949012,...,-0.028278,0.146103,-0.101250,0.781919,0.258258,-0.843708,0.155215,0.121668,57.01,0.0
71395,54281,1.236141,0.256586,0.175963,0.504282,-0.197600,-0.569588,-0.058326,-0.005874,-0.125664,...,-0.263713,-0.821591,0.081703,-0.056701,0.212892,NaN,NaN,NaN,NaN,NaN

In [ ]:
#dataset info
credit_card_data.info()

#checking the number of missing valus in each column
credit_card_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71396 entries, 0 to 71395
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    71396 non-null  int64
 1   V1      71396 non-null  float64
 2   V2      71396 non-null  float64
 3   V3      71396 non-null  float64
 4   V4      71396 non-null  float64
 5   V5      71396 non-null  float64
 6   V6      71396 non-null  float64
 7   V7      71396 non-null  float64
 8   V8      71396 non-null  float64
 9   V9      71396 non-null  float64
 10  V10     71396 non-null  float64
 11  V11     71396 non-null  float64
 12  V12     71396 non-null  float64
 13  V13     71396 non-null  float64
 14  V14     71396 non-null  float64
 15  V15     71396 non-null  float64
 16  V16     71396 non-null  float64
 17  V17     71396 non-null  float64
 18  V18     71396 non-null  float64
 19  V19     71396 non-null  float64
 20  V20     71396 non-null  float64
 21  V21     71396 non-null  float64
 22  V22     71396 non-null  float64
 23  V23     71396 non-null  float64
 24  V24     71396 non-null  float64
 25  V25     71396 non-null  float64
 26  V26     71395 non-null  float64
 27  V27     71395 non-null  float64
 28  V28     71395 non-null  float64
 29  Amount  71395 non-null  float64
 30  Class   71395 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 16.9 MB

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#checking the distribution of legit and fraud transaction
credit_card_data['Class'].value_counts()

Class
0.0    71218
1.0      177
Name: count, dtype: int64

In [ ]:
#separating the data for analyis
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(71218, 31)
(177, 31)

In [ ]:
#statistical measures of the data
legit.Amount.describe()

count    71218.000000
mean        97.028781
std        270.410639
min          0.000000
25%          7.680000
50%         26.550000
75%         88.500000
max      19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     177.000000
mean       95.719153
std       219.167165
min         0.000000
25%         1.000000
50%         7.610000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions

credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,35066.440352,-0.234234,-0.036579,0.704647,0.155872,-0.259090,0.105218,-0.097289,0.048430,0.023374,...,0.044548,-0.031241,-0.106249,-0.038231,0.006499,0.135292,0.022316,0.001788,0.002561,97.028781
1.0,30570.542373,-6.805243,4.918403,-9.162545,5.314564,-5.079731,-2.088712,-7.147266,3.352192,-3.180791,...,0.426844,0.822681,-0.189293,-0.245318,-0.073800,0.248813,0.105956,0.564291,0.045180,95.719153

In [ ]:
legit_sample = legit.sample(n=177)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
51749,45102,-0.940684,0.903703,0.978734,-0.437718,0.876943,1.047219,0.859711,-0.240886,0.607975,...,-0.307423,-0.314469,-0.266982,-1.283902,0.129588,0.241267,-0.495507,-0.304586,26.88,0.0
42846,41271,1.132045,-0.073536,1.172994,1.147711,-0.741022,0.319059,-0.651947,0.244578,0.615576,...,-0.028973,0.099323,-0.060827,0.020753,0.437088,-0.407278,0.069779,0.025492,9.99,0.0
24216,33123,0.914249,-0.056888,1.438735,2.534658,-0.449321,1.422517,-0.792759,0.606187,-0.091796,...,0.041362,0.189383,0.062342,-0.295971,0.089021,-0.004688,0.061309,0.025106,42.13,0.0
47596,43271,-0.801164,0.397471,0.109227,-0.931193,2.677255,3.681962,0.170682,0.948156,0.028626,...,-0.011544,0.023617,-0.097600,1.005281,0.355384,-0.490279,0.036140,0.094585,14.90,0.0
25494,33631,1.297197,0.407301,-0.036750,0.914372,0.227901,-0.461323,0.276148,-0.239837,-0.118359,...,-0.013484,0.055767,-0.218409,-0.414335,0.833604,-0.280249,0.018782,0.014726,7.98,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
68633,53076,1.296231,0.417447,0.193963,0.901644,0.130531,-0.371634,0.158126,-0.202669,-0.079512,...,-0.112114,-0.220002,-0.121022,-0.440454,0.671540,-0.413518,0.032838,0.020600,1.18,1.0
69498,53451,0.385108,1.217620,-1.953872,2.087076,-1.144225,-0.576888,-2.582865,0.643230,-1.191233,...,0.594623,0.372144,-0.310456,-0.624065,0.840216,-0.159452,0.599482,0.288916,8.00,1.0
69980,53658,-1.739341,1.344521,-0.534379,3.195291,-0.416196,-1.261961,-2.340991,0.713004,-1.416265,...,0.383180,-0.213952,-0.336640,0.237076,0.246003,-0.044228,0.510729,0.220952,0.00,1.0
70141,53727,-1.649279,1.263974,-1.050826,2.237991,-2.527889,-0.889940,-2.355254,0.854659,-1.281243,...,0.679176,0.731907,0.333045,0.392505,-0.274197,0.802349,0.390809,0.112146,112.45,1.0
70589,53937,-2.042608,1.573578,-2.372652,-0.572676,-2.097353,-0.174142,-3.039520,-1.634233,-0.594809,...,-0.723326,0.501222,-0.696892,-0.600514,0.127547,-0.786072,0.606097,0.171697,261.87,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    177
1.0    177
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,35062.536723,-0.158644,-0.023595,0.808326,0.215710,-0.140432,0.130671,-0.136632,-0.005285,-0.007859,...,0.050929,-0.054312,-0.063462,-0.030169,-0.031778,0.120922,0.057509,-0.030708,-0.00435,79.054633
1.0,30570.542373,-6.805243,4.918403,-9.162545,5.314564,-5.079731,-2.088712,-7.147266,3.352192,-3.180791,...,0.426844,0.822681,-0.189293,-0.245318,-0.073800,0.248813,0.105956,0.564291,0.04518,95.719153

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class',axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
51749  45102 -0.940684  0.903703  0.978734 -0.437718  0.876943  1.047219
42846  41271  1.132045 -0.073536  1.172994  1.147711 -0.741022  0.319059
24216  33123  0.914249 -0.056888  1.438735  2.534658 -0.449321  1.422517
47596  43271 -0.801164  0.397471  0.109227 -0.931193  2.677255  3.681962
25494  33631  1.297197  0.407301 -0.036750  0.914372  0.227901 -0.461323
...      ...       ...       ...       ...       ...       ...       ...
68633  53076  1.296231  0.417447  0.193963  0.901644  0.130531 -0.371634
69498  53451  0.385108  1.217620 -1.953872  2.087076 -1.144225 -0.576888
69980  53658 -1.739341  1.344521 -0.534379  3.195291 -0.416196 -1.261961
70141  53727 -1.649279  1.263974 -1.050826  2.237991 -2.527889 -0.889940
70589  53937 -2.042608  1.573578 -2.372652 -0.572676 -2.097353 -0.174142

             V7        V8        V9  ...       V20       V21       V22  \
51749  0.859711 -0.240886  0.607975  ...  0.241596 -0.307423 -0.314469
42846 -0.651947  0.244578  0.615576  ... -0.094628 -0.028973  0.099323
24216 -0.792759  0.606187 -0.091796  ... -0.160886  0.041362  0.189383
47596  0.170682  0.948156  0.028626  ... -0.149569 -0.011544  0.023617
25494  0.276148 -0.239837 -0.118359  ... -0.042530 -0.013484  0.055767
...         ...       ...       ...  ...       ...       ...       ...
68633  0.158126 -0.202669 -0.079512  ... -0.029559 -0.112114 -0.220002
69498 -2.582865  0.643230 -1.191233  ...  0.380545  0.594623  0.372144
69980 -2.340991  0.713004 -1.416265  ...  0.002749  0.383180 -0.213952
70141 -2.355254  0.854659 -1.281243  ...  0.087406  0.679176  0.731907
70589 -3.039520 -1.634233 -0.594809  ...  0.825566 -0.723326  0.501222

            V23       V24       V25       V26       V27       V28  Amount
51749 -0.266982 -1.283902  0.129588  0.241267 -0.495507 -0.304586   26.88
42846 -0.060827  0.020753  0.437088 -0.407278  0.069779  0.025492    9.99
24216  0.062342 -0.295971  0.089021 -0.004688  0.061309  0.025106   42.13
47596 -0.097600  1.005281  0.355384 -0.490279  0.036140  0.094585   14.90
25494 -0.218409 -0.414335  0.833604 -0.280249  0.018782  0.014726    7.98
...         ...       ...       ...       ...       ...       ...     ...
68633 -0.121022 -0.440454  0.671540 -0.413518  0.032838  0.020600    1.18
69498 -0.310456 -0.624065  0.840216 -0.159452  0.599482  0.288916    8.00
69980 -0.336640  0.237076  0.246003 -0.044228  0.510729  0.220952    0.00
70141  0.333045  0.392505 -0.274197  0.802349  0.390809  0.112146  112.45
70589 -0.696892 -0.600514  0.127547 -0.786072  0.606097  0.171697  261.87

[354 rows x 30 columns]

In [ ]:
print(Y)

51749    0.0
42846    0.0
24216    0.0
47596    0.0
25494    0.0
        ...
68633    1.0
69498    1.0
69980    1.0
70141    1.0
70589    1.0
Name: Class, Length: 354, dtype: float64

In [ ]:
#split the data into training and testting
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(354, 30) (283, 30) (71, 30)

In [ ]:
#MODEL TRAINING

model = LogisticRegression()

In [ ]:
#training the logistic regression model with Training Data
model = LogisticRegression(max_iter=5000)
model.fit(X_train, Y_train)

LogisticRegression(max_iter=5000)

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data :', training_data_accuracy)

Accuracy on Training data : 0.9681978798586572

In [ ]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy on Testing data :', test_data_accuracy)

Accuracy on Testing data : 0.9295774647887324